export enum PermissionKeysEnum {
  CREATE_USER = 'CREATE_USER',
  CHANGE_USER_STATUS = 'CHANGE_USER_STATUS',
  DELETE_USER = 'DELETE_USER',
  UPDATE_USER = 'UPDATE_USER',
  UPDATE_PROFILE = 'UPDATE_PROFILE',
}
